# Generated by Django 5.1.4 on 2025-01-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_planejamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='controleprocessos',
            table='app_planejamento_controleprocessos',
        ),
    ]
