services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Licitacao360.1000"
      POSTGRES_DB: Licitacao360
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: backend_django
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:@Licitacao360.1000@postgres_db:5432/Licitacao360
    ports:
      - "8000:8000"


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - staticfiles:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  staticfiles:
