# Generated by Django 5.1.4 on 2024-12-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('receita_despesa', models.CharField(max_length=20, verbose_name='Receita/Despesa')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('subtipo', models.CharField(max_length=100, null=True, verbose_name='Subtipo')),
                ('processo', models.CharField(max_length=50, verbose_name='Processo')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situação')),
                ('prorrogavel', models.CharField(max_length=10, verbose_name='Prorrogável')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subcategoria')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('vigencia_inicio', models.DateField(verbose_name='Início da Vigência')),
                ('vigencia_fim', models.DateField(verbose_name='Fim da Vigência')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Inicial')),
                ('valor_global', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Global')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Parcela')),
                ('valor_acumulado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Acumulado')),
                ('fornecedor_nome', models.CharField(max_length=255, verbose_name='Nome do Fornecedor')),
                ('fornecedor_cnpj', models.CharField(max_length=18, verbose_name='CNPJ do Fornecedor')),
                ('orgao_nome', models.CharField(max_length=255, verbose_name='Órgão Contratante')),
                ('unidade_gestora', models.CharField(max_length=255, verbose_name='Unidade Gestora')),
                ('link_historico', models.URLField(verbose_name='Link Histórico')),
                ('link_empenhos', models.URLField(verbose_name='Link Empenhos')),
                ('link_cronograma', models.URLField(verbose_name='Link Cronograma')),
                ('link_faturas', models.URLField(verbose_name='Link Faturas')),
            ],
            options={
                'verbose_name': 'Controle de Contrato',
                'verbose_name_plural': 'Controle de Contratos',
                'ordering': ['numero'],
            },
        ),
    ]
