# Generated by Django 5.1.4 on 2025-01-13 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('unidade_compra', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControleContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('processo', models.CharField(max_length=50, verbose_name='Processo')),
                ('receita_despesa', models.CharField(max_length=20, verbose_name='Receita/Despesa')),
                ('subtipo', models.CharField(max_length=100, null=True, verbose_name='Subtipo')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situação')),
                ('prorrogavel', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prorrogável')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subcategoria')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('vigencia_inicio', models.DateField(verbose_name='Início da Vigência')),
                ('vigencia_fim', models.DateField(verbose_name='Fim da Vigência')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Inicial')),
                ('valor_global', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Global')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Parcela')),
                ('valor_acumulado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Acumulado')),
                ('fornecedor_nome', models.CharField(max_length=255, verbose_name='Nome do Fornecedor')),
                ('fornecedor_cnpj', models.CharField(max_length=18, verbose_name='CNPJ do Fornecedor')),
                ('codigo_orgao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Órgão')),
                ('orgao_nome', models.CharField(max_length=255, verbose_name='Órgão Contratante')),
                ('unidade_compra', models.CharField(blank=True, max_length=20, null=True, verbose_name='UASG')),
                ('sigla_uasg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla da UASG')),
                ('unidade_gestora', models.CharField(max_length=255, verbose_name='Unidade Gestora')),
                ('link_historico', models.URLField(blank=True, null=True, verbose_name='Link Histórico')),
                ('link_empenhos', models.URLField(blank=True, null=True, verbose_name='Link Empenhos')),
                ('link_garantias', models.URLField(blank=True, null=True, verbose_name='Link Garantias')),
                ('link_itens', models.URLField(blank=True, null=True, verbose_name='Link Itens')),
                ('link_prepostos', models.URLField(blank=True, null=True, verbose_name='Link Prepostos')),
                ('link_responsaveis', models.URLField(blank=True, null=True, verbose_name='Link Responsáveis')),
                ('link_faturas', models.URLField(blank=True, null=True, verbose_name='Link Faturas')),
                ('link_ocorrencias', models.URLField(blank=True, null=True, verbose_name='Link Ocorrências')),
                ('link_arquivos', models.URLField(blank=True, null=True, verbose_name='Link Arquivos')),
            ],
            options={
                'verbose_name': 'Controle de Contrato',
                'verbose_name_plural': 'Controle de Contratos',
                'ordering': ['unidade_compra', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_token', models.CharField(blank=True, max_length=64, null=True)),
                ('reset_password_token', models.CharField(blank=True, max_length=64, null=True)),
                ('unidade_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
