# Generated by Django 5.1.4 on 2024-12-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlecontratos',
            options={'ordering': ['uasg', 'numero'], 'verbose_name': 'Controle de Contrato', 'verbose_name_plural': 'Controle de Contratos'},
        ),
        migrations.AddField(
            model_name='controlecontratos',
            name='uasg',
            field=models.CharField(default='000000', max_length=10, verbose_name='UASG'),
        ),
        migrations.AlterField(
            model_name='controlecontratos',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
        migrations.AlterField(
            model_name='controlecontratos',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='controlecontratos',
            name='prorrogavel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Prorrogável'),
        ),
    ]
