# Generated by Django 5.1.4 on 2024-12-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_controlecontratos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nup', models.CharField(max_length=50, unique=True)),
                ('objeto', models.TextField()),
                ('om', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sequencial_pncp', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('irp', models.BooleanField(default=False)),
                ('data_sessao', models.DateField()),
                ('coordenador', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
