# Generated by Django 5.1.4 on 2024-12-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comentario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='uasg',
            field=models.CharField(max_length=50),
        ),
    ]
