# Generated by Django 5.1.4 on 2024-12-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uasg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
