# Generated by Django 5.1.4 on 2024-12-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_planejamento'),
        ('api', '0003_profile'),
    ]

    operations = [
    ]
