# Generated by Django 5.1.4 on 2025-01-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_controleprocessos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControleProcessos',
        ),
    ]
