# Generated by Django 5.1.4 on 2024-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_0003_planejamento_0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planejamento',
        ),
        migrations.AlterField(
            model_name='profile',
            name='validation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
