# app_planejamento/models.py

from django.db import models

class ControleProcessos(models.Model):
    id_processo = models.CharField(max_length=100, primary_key=True)
    tipo = models.CharField(max_length=100)
    numero = models.CharField(max_length=100)
    ano = models.CharField(max_length=100)
    situacao = models.TextField()
    etapa = models.CharField(max_length=100)
    material_servico = models.CharField(max_length=30)
    nup = models.CharField(max_length=100)
    objeto = models.CharField(max_length=100)
    objeto_completo = models.TextField(blank=True, null=True)
    vigencia = models.TextField(blank=True, null=True)
    data_sessao = models.DateField(blank=True, null=True)
    uasg = models.CharField(max_length=10)
    orgao_responsavel = models.CharField(max_length=250)
    sigla_om = models.CharField(max_length=100)
    setor_responsavel = models.TextField(blank=True, null=True)
    responsavel_pela_demanda = models.TextField(blank=True, null=True)
    ordenador_despesas = models.TextField(blank=True, null=True)
    agente_fiscal = models.TextField(blank=True, null=True)
    gerente_de_credito = models.TextField(blank=True, null=True)
    cod_par = models.TextField(blank=True, null=True)
    prioridade_par = models.TextField(blank=True, null=True)
    cep = models.TextField(blank=True, null=True)
    endereco = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    telefone = models.TextField(blank=True, null=True)
    dias_para_recebimento = models.TextField(blank=True, null=True)
    horario_para_recebimento = models.TextField(blank=True, null=True)
    valor_total = models.FloatField(blank=True, null=True)
    acao_interna = models.TextField(blank=True, null=True)
    fonte_recursos = models.TextField(blank=True, null=True)
    natureza_despesa = models.TextField(blank=True, null=True)
    unidade_orcamentaria = models.TextField(blank=True, null=True)
    ptres = models.TextField(blank=True, null=True)
    comentarios = models.TextField(blank=True, null=True)
    justificativa = models.TextField(blank=True, null=True)
    link_pncp = models.TextField(blank=True, null=True)
    link_portal_marinha = models.TextField(blank=True, null=True)
    item_pca = models.TextField(blank=True, null=True)
    portaria_pca = models.TextField(blank=True, null=True)
    data_limite_entrega_tr = models.DateField(blank=True, null=True)
    parecer_agu = models.TextField(blank=True, null=True)
    msg_irp = models.TextField(blank=True, null=True)
    data_limite_manifestacao_irp = models.DateField(blank=True, null=True)
    data_limite_confirmacao_irp = models.DateField(blank=True, null=True)
    num_irp = models.TextField(blank=True, null=True)
    om_participantes = models.TextField(blank=True, null=True)
    srp = models.BooleanField(default=False)
    atividade_custeio = models.BooleanField(default=False)
    prioritario = models.BooleanField(default=False)
    emenda_parlamentar = models.BooleanField(default=False)
    processo_parametrizado = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.id_processo} - {self.objeto}"
    class Meta:
        db_table = "app_planejamento_controleprocessos" 